---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rockylinux9
    image: geerlingguy/docker-rockylinux9-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    D: true
verifier:
  name: ansible
