---
name: CI
on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: egdoc.linux_avatars

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: egdoc.linux_avatars

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install ansible-lint

      - name: Lint role
        run: ansible-lint .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: egdoc.linux_avatars

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install ansible molecule molecule-docker docker

      - name: Run molecule test
        run: molecule test
