name: Release
on:
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: egdoc.linux_avatar

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: egdoc.linux_avatar

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Import role on Galaxy
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d / -f1) $(echo ${{ github.repository }} | cut -d / -f2)
